language: php

branches:
  except:
    - master

branches:
  only:
    - shieldon-psr-http

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.2
  - 7.3

env:
  global:
    - TEST_COMMAND="./vendor/bin/phpunit"
  matrix:
    - SUITE="Shieldon"

branches:
  except:
    - /^analysis-.*$/
    - /^patch-.*$/

before_install:
  - iphpenv config-rm xdebug.ini || true

install:
  - travis_retry composer update --prefer-dist --no-interaction

script:
  - $TEST_COMMAND --testsuite $SUITE
